/run/initialize
/tracking/verbose 1

/run/printProgress 1

/filter/excludeParticle e-
/filter/excludeVolume fs1
/filter/recordWhenHit target

#Using the wall generator
#/generator/spectrum config/generator/rockGammaU238.root
/generator/spectrum ../../rockGammaU238.root
/generator/particle gamma
#can Specify: Top,Bottom,SideRight,SideRight,Front,Back
/generator/surfacename Top
/generator/wall_x 0.5 m
/generator/wall_y 0.5 m
/generator/wall_z 0.5 m


#/gps/particle   ion
#/gps/ion 92 238
#/gps/energy 0 keV

/run/beamOn 10
